Fix Make `PWMMotorMediator` physically realistic #88.
DeepBlueRobotics/DeepBlueSim pull request #102
Opened 2024-07-09 19:29 UTC by brettle

Also fix #100 (use DBSBrake to ensure unique name).

2024-07-09 22:08 UTC, CoolSpy3 requested changes

2024-07-09 22:08 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +                0, 2 * Math.PI), "Shaft close to target rotation");
These two assertions do the same thing in two different ways. We should be consistent about how we check if a double is in a range.

2024-07-09 22:13 UTC, brettle commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +                .invoke(null, 1));
I'm intending to eventually have the test world contain a bunch of flywheels each powered by a different motor. Something like the current code would be called in a loop that iterates over the motor model names.

2024-07-09 22:16 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
Speed is "normalized" to be in the range -1 to +1.

2024-07-09 22:17 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +            motor.getBrake().setDampingConstant(dampingConstant);
Yes. Planned for https://github.com/DeepBlueRobotics/DeepBlueSim/issues/89.

2024-07-09 22:20 UTC, brettle commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +                0, 2 * Math.PI), "Shaft close to target rotation");
The second assertion does the needed modulo arithmetic for the continous angle. That is not needed for the first assertion because it is comparing speeds.

2024-07-09 22:26 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
Oh, yeah *facepalm*

Although, would it make more sense to do something like [what we have in CANMotorMediator](https://github.com/DeepBlueRobotics/DeepBlueSim/blob/10410f59c32ae50a2a4181f274bbec2252fc58fc/plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java#L98-L112)?

2024-07-10 02:30 UTC, brettle commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +    // dw/dt = (V-V_max/w_free*w)/(V_max/(i_stall-i_free))*tau_stall/(i_stall-i_free)/J
Fixed. Fwiw, I'm pretty confident that `computeSpeedRadPerSec()` and `computeAngleRadians()` can be reworked to just be calls to [calculateX](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/system/LinearSystem.html#calculateX(edu.wpi.first.math.Matrix,edu.wpi.first.math.Matrix,double)) on the `LinearSystem` returned by [createDCMotorSystem()](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/system/plant/LinearSystemId.html#createDCMotorSystem(edu.wpi.first.math.system.plant.DCMotor,double,double))​. The derivation could then be replaced with a pointer to [these docs](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/state-space-intro.html#introduction-to-state-space-control). If you think that's a good idea, file an issue so we can do it a separate PR.

The advantage to the current approach is that the reader only needs to know physics and calc to understand the derivation. They don't need to know linear algebra. The disadvantage is that it's a lot more verbose.

2024-07-10 04:30 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
I've added the `switch` from `CANMotorMediator` but not the rest because it's wrong. Consider the available torque it calculates when the user sets the output to 1. It assumes that the motor is already running at full speed and calculates a current of 0 and a resulting available torque of 0.

The correct available torque is the fraction of the max torque that the motor is capable of producing.

2024-07-10 04:30 UTC, brettle commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +    }
Fixed.

2024-07-10 05:51 UTC, brettle commented
@CoolSpy3, I think with my latest commit, I finally have the math correct in *both* the test and the implementation.

2024-07-10 08:04 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
True. However, I don't think the implementation here's right either. `|speed| * t_stall * gearing` means that the motor has more torque at higher speeds (which is not the case). We could try to read the motor speed with an encoder. That would probably be most accurate given that the motor speed changes over time. Although, I'm not sure what we'd do in the case where there is no encoder in Webots. I suppose in that case, we could just fallback on the max torque.

2024-07-10 13:40 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
You're misunderstanding how the code is intended to work. The torque is provided by the combination of the motor and the brake.

2024-07-10 15:26 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
Specifically, consider the diff eq in the derivation:

```
dw/dt = k_T/(R*J)*V - k_T/(R*J)/k_v*w
```

Multiply both sides by `J` to get: 

```
tau = J*dw/dt = k_T/R*V - k_T/(R*k_v)*w
```

The first term is the torque provided by the Webots Motor and the second term is the torque provided by the Webots Brake.

2024-07-10 23:23 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +    // C = theta_0 + (w_0 - w_f)) * t_c
```suggestion
    // C = theta_0 + (w_0 - w_f) * t_c
```

2024-07-10 23:23 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +    // dw/dt = (V-V_max/w_free*w)/(V_max/(i_stall-i_free))*tau_stall/(i_stall-i_free)/J
Tracked at #106

2024-07-10 23:23 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/PWMMotorMediator.java
> +                    * motorConstants.stallTorqueNewtonMeters * gearing);
Ahh, that makes more sense! Thanks for the explanation!

2024-07-10 23:24 UTC, CoolSpy3 requested changes
Looks good! Just some minor formatting notes.

2024-07-10 23:24 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/PWMMotorControllerTest.java
> +    // dw/dt = (V-V_max/w_free*w)/(V_max/(i_stall-i_free))*tau_stall/(i_stall-i_free)/J
Tracked at #106

2024-07-10 23:28 UTC, CoolSpy3 approved these changes

2024-07-10 23:30 UTC, merged