Fix-unrealistic-CANMotorMediator
DeepBlueRobotics/DeepBlueSim pull request #112
Opened 2024-07-13 17:51 UTC by brettle

Currently, CAN motor messages don't seem to be sent over halsim ws.

2024-07-13 17:58 UTC, brettle commented
@CoolSpy3, do you have any idea why SimDevice messages don't appear to be being sent over halsim ws? At the moment, this branch is setup such that:

1. It doesn't use SimHooks.stepTiming() since that was a problem in the past.
2. MotorControllerTest.wbt has an additional flywheel controlled by SparkMax NEO and MotorControllerRobot.java is set up to run it just like the PWMMotorController driven flywheel.
3. The robot controller for MotorControllerTest.wbt is extern to make it easier to test.

When the MotorControllerTest systemTest is run, a breakpoint at the beginning of CANMotorSim.processMessage() never gets hit. Any idea why?

2024-07-13 21:45 UTC, brettle commented
To be clear, the CI tests are just failing because the controller is currently external.

2024-07-13 21:47 UTC, CoolSpy3 commented
Alright, after some testing, I've figured out part of it. You have to add `CommandScheduler.getInstance().run();` to `robotPeriodic()` so that the lib199 periodic methods are run (which push the new motor speeds to halsim). This triggers the breakpoint, but for some reason, I'm still not seeing the motor moving in the sim.

2024-07-13 21:52 UTC, CoolSpy3 commented
I think I found the other bug. Testing now.

2024-07-13 22:07 UTC, CoolSpy3 commented
Try this. For some reason, simulating the extern controller locally is taking an unreasonably long time to process callbacks (i.e. many seconds for my breakpoints to be hit after the robot code sends a message).

2024-07-13 22:37 UTC, brettle commented
I'm still not seeing the breakpoint get hit and the second flywheel doesn't turn. Is it turning for you? I even let the test run for 30 secs instead of just 3 secs. How long is the delay before you see it hit the breakpoint?

2024-07-13 22:53 UTC, brettle commented
Fwiw, I started down this path because I was experiencing a similar problem when trying move the time sync from NT back to hal sim to fix #101. What I saw was seeing was that if I created a `SimDevice` with a `SimDouble` property and then I called `set()` on that `SimDouble`, `SimDeviceSim.processMessage()` was not getting called. Since I was calling `set()` directly, the call to `CommandScheduler.getInstance().run()` should not have been needed for that to work.

2024-07-13 23:13 UTC, CoolSpy3 commented
> I'm still not seeing the breakpoint get hit and the second flywheel doesn't turn. Is it turning for you? I even let the test run for 30 secs instead of just 3 secs. How long is the delay before you see it hit the breakpoint?

It appears to be related to my testing methodology :/ In order to not have to run the full suite, I've been testing by running `./gradlew :tests:simulateJava` with `Main.java` set to `MotorControllerRobot`, and just manually enabling. (I had to add `ws_server.defaultEnabled = true` to `build.gradle`).

With this, the breakpoint in `CANMotorSim.processMessage` is hit continuously from the time that the controller connects to WPILib. The breakpoint I was seeing a delay on was one I placed in the speed callback of `PWMMotorMediator`, which was hit ~17-18 seconds after the start of the test.

If I just run the suite, `CANMotorSim.processMessage` is not called. (Also for some reason, I can't get the `DBSExampleTest (tests)` to work. The robot moves a bit, and then the simulation just freezes. (I suspect it's probably a timing bug.)

2024-07-13 23:38 UTC, CoolSpy3 commented
What I'm Seeing: When running the test, `robotPeriodic()` and `Lib199Subsystem.simulationPeriodic()` are both run periodically, however, `CANMotor` devices (and any other `SimDevice` variants present in this version of the code [ex. `CANEncoder`]) have no data transmitted. This includes the initial statuses which are sent upon device creation and not in the periodic loop. (For reference, even before my changes, these were getting transmitted when `MotorControllerRobot` was run manually.)

2024-07-13 23:43 UTC, brettle commented
Thanks! Although I haven't yet had a chance to try running the robot code outside the tests (my machine is underground an os upgrade at the moment), the behavior you are seeing when running the tests is consistent with what I was seeing. At least I know I'm not crazy! 😄

2024-07-14 00:04 UTC, CoolSpy3 commented
It appears to be caused by [WebotsSimulator:743](https://github.com/DeepBlueRobotics/DeepBlueSim/blob/6770d86ea3ad16717d3f7a1b4cb9b077d2cef44b/plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java#L743) (commenting that line out solves the problem). I'm not sure how though. The callbacks aren't initialized until later, and that method appears to be synchronous.

2024-07-14 00:24 UTC, CoolSpy3 commented
I think I figured it out. When a ws connection is created, `WSProvider_SimDevice` registers device created callbacks so that it can write changes to the network. These are deleted by `SimDeviceSim.resetData()`. Thus, even if the devices are created after the `resetDeviceData()` call, the provider instance is never notified, so no network data is sent. Therefore, if `SimDeviceSim.resetData()` is called after a ws connection is established, sim devices cannot be created on that connection.

2024-07-14 00:41 UTC, brettle commented
Nice work! Thanks!

2024-07-14 23:57 UTC, CoolSpy3 requested changes
Just a couple minor suggestions/cleanup.

2024-07-14 23:57 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java
> +    double lastPosRads = Double.NaN;
```suggestion
```

2024-07-14 23:57 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java
> +    private double dampingConstant = 0.0;
```suggestion
    private double dampingConstant = 0.0;
    private double lastPosRads = Double.NaN;
```

2024-07-14 23:57 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> -            SimDeviceSim.resetData();
Do we want to delete this outright? Given that this makes sense to include for the reproducibility of simulations, it might be better to just comment this out until the wpilib bug is resolved. Alternatively, we could proved a test rule like we have in `lib199` that calls `resetData()` between tests.

2024-07-14 23:57 UTC, CoolSpy3 commented on tests/src/main/java/frc/robot/MotorControllerRobot.java
> +        mockedEncoder.close();
I just approved this PR, so `lib199` can be updated, and this can be removed.

2024-07-14 23:57 UTC, CoolSpy3 commented on tests/src/main/java/frc/robot/MotorControllerRobot.java
> +    private RelativeEncoder m_canEncoder;
`m_canEncoder` is unused

2024-07-14 23:57 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/MotorControllerTest.java
It seems a bit strange to run the tests for both motors simultaneously but require the test to be run twice. However, I can't think of a clean way to get rid of that behavior, so I'm fine with moving that to an issue rather than addressing it here.

2024-07-14 23:57 UTC, CoolSpy3 commented on plugin/controller/src/webotsFolder/dist/protos/deepbluesim/DBSBuiltinEncoderBase.proto
> -    field SFString name ""
Given that they're unused, should we also remove the unconnectedFields in this proto?

2024-07-15 00:03 UTC, brettle commented on tests/src/systemTest/java/frc/robot/MotorControllerTest.java
Yeah. I'd still like to merge the tests, but the more I thought about it the more it seemed too complicated to include in this initial implementation. Separate issue would be good.

2024-07-15 00:16 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> -            SimDeviceSim.resetData();
I think a test rule would still break HALSimWS since the tests are run in the same process (at least if they are in the same class). The test rule works in `lib199` because it isn't using HALSimWS.

Imo, the correct fix to wpilib would probably make `HAL.init()` actually re-initialize the HALSim extensions. If such a fix is adopted, we wouldn't want/need to call `resetData()`.

Regardless, it's not clear to me why we need/want to call `resetData()` since `WebotsSimulator` doesn't deal in `SimDeviceSims`, only `SimDevices`.

2024-07-15 00:47 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> -            SimDeviceSim.resetData();
Actually, the `WSProvider`s are reinitialized on each websocket connection, so when we reset the world, that *should* fix the problem. That being said, I think that trying to call the function after the reset but before the world load might lead to some race conditions, so we can ignore this until the wpilib bug is fixed.

Technically, the actual sim data isn't associated with any of the HALSim extensions, just HALSim core. That being said, I'd be in support of `HALSim.shutdown()` erasing this data.

Under the hood, I'm pretty sure the two are the same, so `resetData()` also clears the `SimDevice` data, which we don't want to retain between sims.

2024-07-15 03:45 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java
> +    private void updateBrakeDampingConstant() {
Fixed.

2024-07-15 03:46 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> -            SimDeviceSim.resetData();
Safely restored one of the calls to resetData(). Restoring the other definitely triggers the problem.

2024-07-15 03:46 UTC, brettle commented on tests/src/main/java/frc/robot/MotorControllerRobot.java
> +        mockedEncoder.close();
Done.

2024-07-15 03:47 UTC, brettle commented on tests/src/main/java/frc/robot/MotorControllerRobot.java
> +    private RelativeEncoder m_canEncoder;
Fixed.

2024-07-15 03:47 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/deepbluesim/DBSBuiltinEncoderBase.proto
> -    field SFString name ""
Done.

2024-07-15 03:47 UTC, brettle commented
I think I've addressed everything.

2024-07-15 05:51 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> -            SimDeviceSim.resetData();
Correction, that one can't be safely restored and has been removed.

2024-07-15 06:47 UTC, CoolSpy3 approved these changes
Looks good!

2024-07-15 06:48 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/MotorControllerTest.java
Tracked at #115.

2024-07-15 13:28 UTC, merged