Use-halsim-for-time-sync
DeepBlueRobotics/DeepBlueSim pull request #114
Opened 2024-07-15 05:44 UTC by brettle

Works but each run takes an additional 3 seconds to startup. Time appears to be taken up in wpilib between when the robot program starts and when waitForUserToStart() is called (i.e. the first periodic event).

2024-07-15 22:49 UTC, CoolSpy3 requested changes

2024-07-15 22:49 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +        }
This should also probably call `listenerCallbackExecutor.shutdown()`.

2024-07-15 22:49 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +                        stepSimulation(robot, basicTimeStep);
Why do we need to perform a step after the world load? Shouldn't the controller just terminate? If it's just to process the reload request, it might make more sense to just do `robot.step(0)` rather than also calling all periodic methods / performing a full step.

2024-07-15 22:49 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
>                              inst.flush();
This is no longer necessary.
```suggestion
```

2024-07-16 00:17 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +                            SimHooks.stepTiming(0);
Would rather leave this as is so that the notification isn't put at the end of the queue.

2024-07-16 02:43 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +                        stepSimulation(robot, basicTimeStep);
I am not entirely sure why we need to take the step (and not just a 0 step), but the reload definitely doesn't happen if we don't take that step. Calling the periodic methods isn't necessary though, so I've removed that.

2024-07-16 02:44 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +        }
Fixed.

2024-07-16 02:44 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
>                          ensureRobotTimingStarted();
Fixed.

2024-07-16 02:44 UTC, brettle commented
I think I've addressed everything. Thanks for the review!

2024-07-16 02:54 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +                            SimHooks.stepTiming(0);
In that case, should we instead make it so `sendRobotTime()` does not queue it's body because it's only ever called from within the queue?

2024-07-16 16:34 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +                            SimHooks.stepTiming(0);
Fixed.

2024-07-17 21:36 UTC, CoolSpy3 approved these changes

2024-07-17 21:40 UTC, merged