Workaround HALSimWS SimDevice deadlocks.
DeepBlueRobotics/DeepBlueSim pull request #118
Opened 2024-07-16 21:02 UTC by brettle

Includes PR #114 and PR #117. Fixes issue #113.

The critical change here is calling waitForUserToStart() *before* creating the robot. That gives the controller's HALSimWS client a chance to connect before the SimDevices are created. Before that change, I'd get a deadlock at ~1/7 of the time. With that change, I've run over 137 times in a row without a deadlock.

2024-07-16 23:34 UTC, brettle commented
Fyi, I have over 142 consecutives runs without deadlock on my local machine with the latest commit.

2024-07-17 19:48 UTC, brettle commented
Despite my test results, it turns out that this is not sufficient avoid deadlocks. The issue is that even well after the HALSimWS connection has been established and is quiet, if SimDevice.create() is called, it will trigger the HALSimWS server thread to call the onConnect() callback for the new device and that can deadlock with the thread that called SimDevice.create(). In short, if there is a HALSimWS connection when SimDevice.create() is called, there could be a deadlock. As a result, a workaround will be a bit more involved. I'm going to work on that in a new PR which builds on this and PR (and PR #119 because that PR makes it faster to do repeated tests). I'd still like this PR merged though, since I'll be building on it.

2024-07-17 22:36 UTC, CoolSpy3 requested changes

2024-07-17 22:36 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +            Supplier<WebSocketClient> halSimWSClientSupplier) {
There's no reason that both `DeepBlueSim` and `WebotsSupervisor` have to mange the ws connection. Originally, I was going to suggest moving all of the shutdown code to `DeepBlueSim` because (atm) that can be done fairly easily. However, given that it looks like `WebotsSupervisor` is going to have to be doing more to  work around the halsim deadlock, I think it makes sense to just move all of the ws management to this class.

2024-07-17 22:36 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +                        delayer.cancel();
We should just move all of these to `close()`.

2024-07-17 22:36 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +            }, minQuietTimeMs);
Could be changed to `minQuietTimeMs - timeSinceLastMsgMs`, but given that it doesn't really hurt to err of the side of waiting longer here, I don't have a problem with keeping it as-is.

2024-07-17 22:36 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +    private static final long minQuietTimeMs = 500;
This should be moved to the top of the file.

2024-07-17 22:42 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +            Supplier<WebSocketClient> halSimWSClientSupplier) {
Would like to handle that as part of PR #120.

2024-07-17 22:43 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +            }, minQuietTimeMs);
That was my thinking. Also, it ensures that some sort of rounding issue doesn't put us in effectively an infinite loop.

2024-07-17 22:53 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +                        delayer.cancel();
Agreed but would like to handle as part of PR #120 since I have other changes in the same area and would rather not deal with the merge conflict.

2024-07-17 22:53 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/WebotsSupervisor.java
> +    private static final long minQuietTimeMs = 500;
Fixed.

2024-07-17 22:55 UTC, CoolSpy3 approved these changes

2024-07-17 22:57 UTC, merged