Add PoweredHinge2Joint
DeepBlueRobotics/DeepBlueSim pull request #131
Opened 2024-07-23 16:27 UTC by brettle

2024-07-28 03:20 UTC, brettle commented
Note: tests pass locally. CI is failing because it is using Webots R2023b.

2024-07-29 15:47 UTC, brettle commented
@CoolSpy3, please review when you have a chance.

2024-07-29 22:28 UTC, CoolSpy3 requested changes

2024-07-29 22:28 UTC, CoolSpy3 commented on tests/src/systemTest/java/frc/robot/MotorControllerTest.java
> +                    .run();
It looks like we're no longer asserting the correct shaft position/rotation. Is just checking the time constant enough for this test?

2024-07-29 22:56 UTC, brettle commented on README.md
> + 1. Install [this unofficial version](https://github.com/DeepBlueRobotics/webots/releases/tag/R2024a_DeepBlueSim_2024_07_29) of Webots which contains fixes needed by DeepBlueSim. The latest [official
Fixed. If we get bug reports that we can't reproduce, we can ask the reporter to try a specific build.

2024-07-29 23:05 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/Watcher.java
> +    Vector<N3> getAngularVelocity() {
Because a `Rotation3d` 1) represents a *sequence* of 3 rotations (around x, then y, then z), 2) does not contain a `norm()` method, and 3) contains various methods that don't apply to an angular velocity. I briefly changed it to a `Translation3d`, but in the end decided that was even more confusing.

2024-07-29 23:13 UTC, brettle commented on tests/src/systemTest/java/frc/robot/MotorControllerTest.java
> +                    .run();
Imo, yes this is sufficient. I wasted a *lot* of time trying to get the shaft position/speed assertions to work with the `PoweredHinge2Joint`, before finally realizing that there were other sources of error other than time jitter. Most importantly there is the simulator's [accumulated integration error](https://en.wikipedia.org/wiki/Euler_method#Global_truncation_error) and trying to account for that just doesn't seem worth the effort. The reality is that any meaningful bug I can imagine would significantly impact the measured time constant, so this should be sufficient. It's also simpler and less code to read/maintain.

2024-07-30 03:40 UTC, CoolSpy3 approved these changes

2024-07-30 03:40 UTC, merged