Fix to work with spec compliant CAN sims.
DeepBlueRobotics/DeepBlueSim pull request #53
Opened 2024-05-23 00:26 UTC by brettle

Rename SimDeviceEncoderMediator.java to CANEncoderMediator.java.

Rename SimDeviceMotorMediator.java to CANMotorMediator.java.

Add DutyCycleMediator.java to handle SparkMaxAbsoluteEncoder and CANCoder devices.

Add AnalogInputMediator.java to handle SparkMaxAnalogSensor devices.

Currently passes system test but that doesn't test any of the new functionality.

2024-05-23 00:28 UTC, brettle commented
Includes PR #50 and PR #49.

2024-05-24 04:55 UTC, CoolSpy3 requested changes

2024-05-24 04:55 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/SimRegisterer.java
> +            if (node.getTypeName().equals("SparkMaxAlternateEncoder")) {
Given that we're adding support for SparkFlexes, it probably makes sense to rename a lot of these. However, that might be better suited for another pr.

2024-05-24 04:55 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/mediators/AnalogInputMediator.java
Could we rename this to `AnalogInputEncoderMediator` to reflect the fact that it mediates encoders and not generic analog sources?

2024-05-24 04:55 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/mediators/CANMotorMediator.java
> +        if(motor.getName().startsWith("DBSim_Motor_Spark ")) {
To be consistent with the check in `SimRegisterer.java`
```suggestion
        if(motor.getName().startsWith("DBSim_Motor_Spark")) {
```

2024-05-24 04:55 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/mediators/CANMotorMediator.java
>      }
To ensure spec compliance, we should also send `busVoltage = 12`.

2024-05-24 20:18 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/mediators/CANMotorMediator.java
>      }
Fixed now.

2024-05-25 00:00 UTC, CoolSpy3 approved these changes

2024-05-25 00:04 UTC, merged