Add libdeepbluesim
DeepBlueRobotics/DeepBlueSim pull request #74
Opened 2024-06-02 18:35 UTC by brettle

2024-06-10 10:36 UTC, CoolSpy3 commented
I'm not sure if you've looked into it, but I did some digging into the build error.

It looks like `WpilibTools` is being loaded as part of `controller` *and* `libdeepbluesim`, and the two are conflicting. [On windows, `WpilibTools` tries to make a cast of `ExtractEmbeddedWindowsHelpers`](https://github.com/wpilibsuite/wpilib-tool-plugin/blob/d767e8518cebcea04e871f0dc0cd5924d8560f77/src/main/java/edu/wpi/first/tools/ExtractConfiguration.java#L139). `ExtractEmbeddedWindowsHelpers_Decorated` is a class created by Gradle which extends `ExtractEmbeddedWindowsHelpers`. However, because `WpilibTools` is loaded twice, it registers two versions of the `extractEmbeddedWindowsHelpers` class (both in the root project). Then, whichever one was loaded first attempts to cast the version of the task loaded by the second, which fails because the two are from different class loaders.

(Side note: If you move just the plugin declaration to `plugin/build.gradle`, the error becomes apparent with a message stating that the `extractEmbeddedWindowsHelpers` cannot be recreated a second time.)

I attempted a quick-fix by moving all of the `WpilibTools` code to `plugin/build.gradle`. This fixes the build, but causes the natives to not be loaded at runtime. I might look at it a bit more tomorrow, but I'm not sure how far I'll get, so feel free to investigate as well. However, for now, I'm gonna call it a night.

2024-06-10 17:09 UTC, brettle commented
I actually hadn't even seen that there was a build failure. Many thanks for the late night investigation!

Feel free to keep investigating. I probably won't look into it right away. Consider opening an issue with wpilib-tool-plugin and perhaps providing a minimal test case.

As a workaround, would it help if `libdeepbluesim.jar` was built as part of the controller project (ie not as a separate project)? There are various constant values (eg names of NT entries) that are shared between the 2 jars, so having `DeepBlueSim.jar` depend on `libdeepbluesim.jar` might not be a bad thing. I'd like to keep `libdeepbluesim.jar` as a thin jar if possible and if `DeepBlueSim.jar` is going to include `libdeepbluesim.jar`, I'd _prefer_ if it didn't also include any transitive dependencies (since it really just needs those few constants).

Another tangentially related thing that might be worth investigating is having the plugin generate/update Webot's [runtime.ini](https://cyberbotics.com/doc/guide/controller-programming#environment-variables) file for the controller. That might obviate the need to extract the native libs if it can be used to point Webots at them directly.

2024-06-10 22:09 UTC, CoolSpy3 commented
I actually managed to find a workaround by declaring the `WpilibTools` dependency in `:plugin`. I've got a thought for a possible fix, so I'll work on a PR for WpilibTools.

2024-06-25 00:01 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpilibTools.deps.wpilibJava("wpimath")
This should probably be api instead of implementation because some public methods return `Translation3d` and `Rotation3d` objects.

2024-06-25 00:04 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpi.java.deps.wpilib()
This should be api because `WebotsSimulator.run()` takes a `TimedRobot`.

2024-06-25 00:05 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpi.java.vendor.java()
This probably isn't needed.

2024-06-25 14:41 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpilibTools.deps.wpilibJava("wpimath")
Fixed.

2024-06-25 14:41 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpi.java.deps.wpilib()
Fixed.

2024-06-25 14:41 UTC, brettle commented on plugin/libdeepbluesim/build.gradle
> +    implementation wpi.java.vendor.java()
Fixed.

2024-06-25 23:46 UTC, brettle commented
@CoolSpy3, just in case you missed it, this is ready for review.

2024-06-25 23:56 UTC, CoolSpy3 commented
> @CoolSpy3, just in case you missed it, this is ready for review.

Yeah, I've been working my way through it. I've gotten a bit sidetracked atm by a Webots bug that popped up during testing, but I've got 1 more file to review and a bunch of logging suggestions that I'm moving to another PR. Should, hopefully, be done by EOD.

2024-06-26 01:55 UTC, CoolSpy3 requested changes
Nice! I'm happy with the general layout of the API, I mostly just have notes on a couple specifics. I also had a bunch of minor (oneliner) suggestions that I moved to #80.

The one overall critique: As is, this breaks console output when run as an extern controller. My initial thought on how to fix this would be to only overwrite `java.util.logging.config.file` if it exists and then specify the path to the config file in the VSCode run task as a jvm arg, but there might be other ways too. (This method has the nice side effect of enabling console output at the INFO level by default if a config file is not found [albeit with, imo, a slightly worse format string])

2024-06-26 01:55 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    waitUntilFlushed();
I'm assuming the idea here is to close the publishers so that previously published values aren't sent to a new server. If that's the case, a comment should be added to that effect.

2024-06-26 12:34 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    inst.close();
Just good hygiene.

2024-06-26 13:00 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    inst.close();
Also added a comment.

2024-06-26 13:00 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    inst = NetworkTableInstance.getDefault();
Added a comment.

2024-06-26 13:01 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    inst.close();
Added a comment.

2024-06-26 13:01 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +    private static int ntLogLevel = LogMessage.kInfo;
Fixed.

2024-06-26 13:01 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +    private static int ntLogLevel = 0;
Fixed.

2024-06-26 13:01 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +            while (oscb != null) {
Fixed.

2024-06-26 13:01 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    waitUntilFlushed();
Added a comment.

2024-06-26 20:35 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +    private static void reportKinematicsForAllWatchedNodes(
With this method being removed, `reportKinematicsFor(Node, NetworkTable)` is now unused (and should, presumably be removed?).

However, in general, I'm not sure where the kinematics values are being updated after the first initialization. In my mind, the *second* invocation to one of the getters follows the path:
``` Java
// Callback is passed a SimulationState object and calls
SimulationState.<value>(String); // which calls
Watcher.getByDef(String); // which returns the cached Watcher instance and calls
Watcher.get<Value>(); // which calls
<value>Ready.join(); // which returns instantly because the future was completed on the first invocation
// NT value is returned
```
At no point in this chain is any value written to NT, so `watchedNodesSubscriber` (WebotsSupervisor:126) never registers any events, so `report<Value>For(Node, NetworkTable)` is never called, so the values returned by `Watcher` will be stale. Originally, my thought was that `reportKinematicsForAllWatchedNodes` would be invoked every step, solving this problem. (Even though Watcher still wouldn't synchronize on the new values, being updated every step would probably make the most recent values close *enough* for most applications.)

2024-06-26 20:39 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +    public static class SimulationState implements AutoCloseable {
Fair. In that case, would it make sense to only generate a single `SimulationState` instance per step rather than one for every callback invocation?

2024-06-26 20:46 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +    private static void reportKinematicsForAllWatchedNodes(
`Watcher.getByDef() `calls `Watcher.reset()` which creates new `CompleteableFutures`.

2024-06-26 20:49 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +    private static void reportKinematicsForAllWatchedNodes(
Ah, I missed that! In that case, `reportKinematicsFor(Node, NetworkTable)` can just be removed :+1:

2024-06-26 20:56 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/Watcher.java
> +        rotationReady.join();
```suggestion
        velocityReady.join();
```

2024-06-26 23:38 UTC, brettle commented on plugin/controller/src/main/java/org/team199/deepbluesim/WebotsSupervisor.java
> +                    inst.setServer("localhost");
Considered that but felt it was better to leave it like this even though there is a very small amount of duplicated code. Moving `startNetworkTablesClient()` to `WebotsSupervisor` would mean that `DeepBlueSim` would need to call into `WebotsSupervisor` even with -`-no-robot-code`, and that would be the _only_ reason it was doing so. Leaving it in `DeepBlueSim` would mean that `WebotsSupervisor` would depend on `DeepBlueSim`, but _only_ to start network tables. So it just seemed like an unnecessary dependency to avoid duplicating 2 lines of code.

2024-06-26 23:59 UTC, brettle commented
> As is, this breaks console output when run as an extern controller.

Won't the extern controller just read whatever `logging.properties` that is in the current working directory? If so, why is that a problem?

2024-06-27 00:01 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/Watcher.java
> +            synchronized (Watcher.class) {
Fixed.

2024-06-27 00:01 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/Watcher.java
> +        synchronized (Watcher.class) {
Fixed.

2024-06-27 00:02 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +    private boolean useStepTiming = true;
Added a comment describing why I'd rather not.

2024-06-27 00:02 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +    public static class SimulationState implements AutoCloseable {
I like! Changed.

2024-06-27 00:26 UTC, CoolSpy3 commented
> Won't the extern controller just read whatever logging.properties that is in the current working directory? If so, why is that a problem?

Specifically, I'm concerned about the VSCode run/debug task. I've gotten into the habit of using it when debugging the controller, and not having command line output makes debugging harder. ATM, the working directory for that task is the project root, so `logging.properties` does not exist, causing nothing to be logged. My initial thought was that we could configure it with `-Djava.util.logging.config.file`, however, it occurs to me now that what we could do is change the working directory for that task to be the controller directory, which actually might make sense to do anyways. (Although having a cli option might be useful as well.)

2024-06-27 00:28 UTC, CoolSpy3 commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +
These changes should also be made to `WebotsSupervisor`.

2024-06-27 00:50 UTC, brettle commented on plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java
> +
Fixed.

2024-06-27 01:01 UTC, brettle commented
> Specifically, I'm concerned about the VSCode run/debug task. I've gotten into the habit of using it when debugging the controller, and not having command line output makes debugging harder. ATM, the working directory for that task is the project root, so `logging.properties` does not exist, causing nothing to be logged.

Fwiw, I thought that would cause the default `logging.properties` from `~/wpilib/2024/jdk/conf/` to be used. Looks like that puts `INFO` level logs to the console.

> change the working directory for that task to be the controller directory, which actually might make sense to do anyways. 

Sounds good. I've attempted to do that in my latest commit, but running the debug task is failing for me for unrelated reasons, so I can't test at the moment. If my commit isn't what you are looking for, please make the change yourself since you are in a position to test it.

> (Although having a cli option might be useful as well.)

If you real want it I'm not going to stop you, but seems like it is convenient to know that the controller is running from the dir that it would run from as a non-extern controller.

2024-06-27 01:13 UTC, CoolSpy3 approved these changes
> Sounds good. I've attempted to do that in my latest commit, but running the debug task is failing for me for unrelated reasons, so I can't test at the moment. If my commit isn't what you are looking for, please make the change yourself since you are in a position to test it.

Your commit fixes the functionality for me!

> If you real want it I'm not going to stop you, but seems like it is convenient to know that the controller is running from the dir that it would run from as a non-extern controller.

Yeah, this is probably the best method anyways. We can deal with the CLI later if it becomes a necessity.

2024-06-27 01:13 UTC, merged