Add-support-for-linear-motors
DeepBlueRobotics/DeepBlueSim pull request #82
Opened 2024-06-30 17:20 UTC by brettle

- Extract common motor proto def into wpimotor.js.
- Add WPILinearMotorBase.proto, MiniCIMLinearMotor.proto, and NEOLinearMotor.proto.
- Start extracting motor specs into wpimotor.js. Only MiniCIM and NEO done so far.
- Add elevator to robot.
- Add simple smoke test.

2024-06-30 17:22 UTC, brettle commented
@CoolSpy3, although this isn't yet complete, please take a look and let me know if you have questions/concerns about the direction I'm headed. Thanks!

2024-06-30 19:37 UTC, brettle commented
Actually, I think is ready for review now.

2024-07-01 06:30 UTC, CoolSpy3 requested changes
Looks good! Just a few minor notes.

Also, given that all the configs are now in a single js file, would it make sense to just have a singular `WPILinearMotor` and `WPIRotationalMotor` that extend their respective base classes and provide a dropdown to select the motor type, or is that just me oversimplifying?

2024-07-01 06:30 UTC, CoolSpy3 commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java
A comment should be added somewhere explaining that `gearing` includes the necessary unit conversion factor (if any). (A similar comment should be applied to `PWMMotorMediator`.)

2024-07-01 06:30 UTC, CoolSpy3 commented on plugin/controller/src/webotsFolder/dist/protos/PoweredHingeJoint.proto
Atm, this gives a template regeneration error if `node_name === null` (when no motor object is present). There should probably be a more descriptive error message.

2024-07-01 06:30 UTC, CoolSpy3 commented on plugin/controller/src/webotsFolder/dist/protos/PoweredSliderJoint.proto
Atm, this gives a template regeneration error if `node_name === null` (when no motor object is present). There should probably be a more descriptive error message.

2024-07-01 06:30 UTC, CoolSpy3 commented on plugin/controller/src/webotsFolder/dist/protos/PoweredHingeJoint.proto
This should probably use `===` and `!==` rather than `==` and `!=`.

2024-07-01 06:30 UTC, CoolSpy3 commented on plugin/controller/src/webotsFolder/dist/protos/PoweredSliderJoint.proto
This should probably use `===` and `!==` rather than `==` and `!=`.

2024-07-01 11:58 UTC, brettle commented on plugin/controller/src/main/java/org/carlmontrobotics/deepbluesim/mediators/CANMotorMediator.java
Done.

2024-07-01 11:58 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/PoweredHingeJoint.proto
Done.

2024-07-01 11:58 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/PoweredSliderJoint.proto
Done.

2024-07-01 11:58 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/PoweredHingeJoint.proto
Done.

2024-07-01 11:58 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/PoweredSliderJoint.proto
Done.

2024-07-01 11:59 UTC, brettle commented
> would it make sense to just have a singular `WPILinearMotor` and `WPIRotationalMotor` that extend their respective base classes and provide a dropdown to select the motor type, or is that just me oversimplifying?

I *really* like that idea but would prefer to leave it for a separate PR.

2024-07-01 13:23 UTC, brettle commented on plugin/controller/src/webotsFolder/dist/protos/PoweredSliderJoint.proto
Fixed now.

2024-07-01 20:51 UTC, CoolSpy3 approved these changes

2024-07-01 20:51 UTC, merged